"""
QLoRA fine-tune Qwen2.5-1.5B on Vietnamese poetry — v5 FIXED.

Key fixes over v5 original:
  - Syllable-level tokenization: adds Vietnamese syllables as single tokens
    to prevent BPE fragmentation (garbled output like "trắngồngọc")
  - Stage 1 uses LB-only corpus (corpus_luc_bat.txt) — no TN dilution
  - Content-weighted loss (P6): tags ×0.3, content ×1.0, <|linebreak|> ×1.2
  - N-gram diversity loss (P7): penalizes repetition during training
  - Scheduled sampling with control token protection

Usage:
  python train.py --stage 1
  python train.py --stage 2 --resume /tmp/checkpoints/qwen_stage1_best
"""

import argparse
import json
import math
import os
import re
import time
from pathlib import Path

import torch
import torch.nn.functional as F
from tqdm import tqdm

# ═══════════════════════════════════════════════════════════════
#  PATH CONFIG (all paths relative to /app inside container)
# ═══════════════════════════════════════════════════════════════

APP_DIR = Path(os.environ.get("APP_DIR", str(Path(__file__).resolve().parent)))
CORPUS_DIR = Path(os.environ.get("CORPUS_DIR", str(APP_DIR / "corpus")))
CHECKPOINT_DIR = Path(os.environ.get("CHECKPOINT_DIR", str(APP_DIR / "checkpoints")))

# v5 FIX: Stage 1 uses LB-only to prevent TN dilution
STAGE_CORPUS = {
    1: CORPUS_DIR / "corpus_luc_bat.txt",       # was: poetry_corpus.txt (mixed)
    2: CORPUS_DIR / "corpus_luc_bat.txt",
}
# Syllable vocab (generated by preprocess_syllables.py)
SYLLABLE_VOCAB_PATH = CORPUS_DIR / "syllable_vocab.json"

MODEL_ID = "Qwen/Qwen2.5-1.5B"
# Only create checkpoint dir when actually running training (import-safe)
# CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)  # moved to train()

# ═══════════════════════════════════════════════════════════════
#  CONFIG
# ═══════════════════════════════════════════════════════════════

STAGE_CONFIGS = {
    1: {"max_steps": 5000, "lr": 2e-4, "patience": 5},
    2: {"max_steps": 2000, "lr": 1e-4, "patience": 3},
}

LORA_CONFIG = {
    "r": 16, "lora_alpha": 32, "lora_dropout": 0.05,
    "target_modules": ["q_proj", "k_proj", "v_proj", "o_proj",
                       "gate_proj", "up_proj", "down_proj"],
    "modules_to_save": ["embed_tokens", "lm_head"],  # 214 control tokens need trainable embeddings (0.66M params)
    "task_type": "CAUSAL_LM",
}

QLORA_CONFIG = {
    "load_in_4bit": True,
    "bnb_4bit_compute_dtype": torch.bfloat16,
    "bnb_4bit_quant_type": "nf4",
    "bnb_4bit_use_double_quant": True,
}

TRAIN_CONFIG = {
    "batch_size": int(os.environ.get("TRAIN_BATCH_SIZE", "4")),
    "gradient_accumulation_steps": int(os.environ.get("TRAIN_GRAD_ACCUM", "4")),
    "block_size": int(os.environ.get("TRAIN_BLOCK_SIZE", "128")),
    "warmup_steps": 100,
    "min_lr": 1e-6,
    "eval_interval": 200,
    "grad_clip": 1.0,
    "num_workers": int(os.environ.get("TRAIN_NUM_WORKERS", "4")),
    "device": "cuda" if torch.cuda.is_available() else "cpu",
}

# ═══════════════════════════════════════════════════════════════
#  v4.2.3 TRAINING IMPROVEMENT CONFIG
# ═══════════════════════════════════════════════════════════════

# P6: Content-weighted loss — tags ×0.3, content ×1.0
# P7: N-gram diversity loss weight
# P8: Linebreak position reinforcement bonus
DIVERSITY_LOSS_WEIGHT = 0.03      # P7 weight
DIVERSITY_WARMUP = 500            # P7 warmup steps
DIVERSITY_WINDOW = 16             # P7 context window
DIVERSITY_SAMPLES = 512           # P7 random samples per step
TAG_LOSS_WEIGHT = 0.3             # P6: weight for control tokens (not <|end|> or <|lb|>)
LINEBREAK_BONUS = 0.2             # P8: extra weight on <|linebreak|> positions


# ═══════════════════════════════════════════════════════════════
#  SPECIAL TOKENS (same 335 as the original train_bpe.py)
# ═══════════════════════════════════════════════════════════════

def collect_rhyme_groups(corpus_path):
    rhymes = set()
    with open(corpus_path) as f:
        for line in f:
            for m in re.finditer(r'\[RHYME:(\w+)\]', line):
                r = m.group(1)
                if all(c.isalpha() for c in r) and len(r) >= 1:
                    rhymes.add(r)
    return sorted(rhymes)


def collect_tone_patterns(corpus_path):
    tones = set()
    with open(corpus_path) as f:
        for line in f:
            for m in re.finditer(r'\[TONE:([BT]+)\]', line):
                tones.add(m.group(1))
    return sorted(tones)


def collect_doi_am_patterns(corpus_path):
    TRAC = set('áắấéếíóốớúứýạặậẹệịọộợụựỵảẳẩẻểỉỏổởủửỷãẵẫẽễĩõỗỡũữỹ'
               'ÁẮẤÉẾÍÓỐỚÚỨÝẠẶẬẸỆỊỌỘỢỤỰỴẢẲẨẺỂỈỎỔỞỦỬỶÃẴẪẼỄĨÕỖỠŨỮỸ')
    def get_tone(syl):
        for ch in syl:
            if ch in TRAC: return 'T'
        return 'B'
    patterns = set()
    with open(corpus_path) as f:
        for line in f:
            if '[THAT_NGON]' in line and '<|reply|>' in line:
                parts = line.split('<|reply|>')
                if len(parts) >= 2:
                    resp = parts[1].split('<|end|>')[0].strip()
                    tones = ''.join(get_tone(s) for s in resp.split()[:7])
                    if len(tones) == 7:
                        patterns.add(tones)
    return sorted(patterns)


def build_special_tokens(corpus_path):
    core = ["<|pad|>", "<|start|>", "<|reply|>", "<|end|>",
            "[LUC_BAT]", "[TU_TUYET]", "[THAT_NGON_BAT_CU]", "[THAT_NGON]"]
    rhyme = [f"[RHYME:{r}]" for r in collect_rhyme_groups(corpus_path)]
    tone = [f"[TONE:{t}]" for t in collect_tone_patterns(corpus_path)]
    doi_am = [f"[DOIAM:{d}]" for d in collect_doi_am_patterns(corpus_path)]
    link = ["[LINK2:B]", "[LINK2:T]"]
    all_tokens = core + rhyme + tone + doi_am + link
    print(f"Special tokens: Core={len(core)} Rhyme={len(rhyme)} "
          f"Tone={len(tone)} ĐốiÂm={len(doi_am)} Link2={len(link)} → {len(all_tokens)} total")
    return all_tokens


# ═══════════════════════════════════════════════════════════════
#  v5 FIX: SYLLABLE TOKENIZATION
# ═══════════════════════════════════════════════════════════════

def load_syllable_vocab(vocab_path):
    """Load syllable vocabulary from JSON file.
    Returns list of syllable strings sorted by frequency (most common first).
    """
    if not vocab_path.exists():
        print(f"⚠️  Syllable vocab not found: {vocab_path}")
        print("   Run: python src/finetune/preprocess_syllables.py")
        return []
    
    with open(vocab_path, encoding='utf-8') as f:
        vocab = json.load(f)  # [[syllable, count], ...]
    
    syllables = [s for s, c in vocab]
    print(f"📖  Loaded {len(syllables):,} syllable candidates from {vocab_path}")
    return syllables


def add_syllable_tokens(tokenizer, syllable_vocab, max_new=5000):
    """
    Add Vietnamese syllables as single tokens to Qwen's tokenizer.
    
    Only adds syllables that Qwen's BPE tokenizer would split into
    multiple tokens. Syllables already present as single tokens are skipped.
    
    Returns: (num_added, list_of_syllable_tokens, token_ids_map)
      token_ids_map: {syllable: (new_token_id, [sub_token_ids])} for smart init
    """
    if not syllable_vocab:
        return 0, [], {}
    
    tokens_to_add = []
    token_ids_map = {}  # syllable → (new_id, sub_token_ids_for_init)
    already_single = 0
    
    print(f"🔍  Checking {len(syllable_vocab):,} syllables against Qwen tokenizer...")
    
    check_limit = min(len(syllable_vocab), max_new * 3)
    
    for syl in syllable_vocab[:check_limit]:
        if len(tokens_to_add) >= max_new:
            break
        
        token_ids = tokenizer.encode(" " + syl, add_special_tokens=False)
        
        if len(token_ids) == 1:
            already_single += 1
        elif len(token_ids) > 1:
            tokens_to_add.append(syl)
            token_ids_map[syl] = token_ids  # save sub-token IDs for smart init
    
    if already_single > 0:
        pct = already_single / min(len(syllable_vocab), check_limit) * 100
        print(f"   Already single tokens: {already_single:,} ({pct:.0f}%)")
    
    if not tokens_to_add:
        print(f"✅  All syllables are already single tokens in Qwen's vocab! No additions needed.")
        return 0, [], {}
    
    print(f"   Need to add: {len(tokens_to_add):,} syllables as special tokens")
    
    num_added = tokenizer.add_tokens(tokens_to_add, special_tokens=True)
    vocab_after = len(tokenizer)
    print(f"   Added: {num_added:,} tokens | Vocab now: {vocab_after:,}")
    print(f"   Examples: {tokens_to_add[:10]}")
    
    return num_added, tokens_to_add, token_ids_map


def init_syllable_embeddings(model, tokenizer, tokens_added, token_ids_map):
    """
    Smart initialization: set new syllable token embeddings to the average
    of their BPE sub-token embeddings from the original Qwen model.
    
    This prevents random-init overfitting: instead of training 5K embeddings
    from scratch, they start from a meaningful average of existing knowledge.
    """
    if not tokens_added or not token_ids_map:
        return
    
    embed_weight = model.get_input_embeddings().weight  # (vocab_size, hidden_dim)
    lm_head_weight = model.get_output_embeddings().weight  # (vocab_size, hidden_dim)
    
    initialized = 0
    for syl in tokens_added:
        new_id = tokenizer.encode(" " + syl, add_special_tokens=False)
        if len(new_id) != 1:
            continue  # should be single token now
        new_id = new_id[0]
        
        sub_ids = token_ids_map.get(syl, [])
        if not sub_ids or new_id >= embed_weight.shape[0]:
            continue
        
        # Average the sub-token embeddings (skip ids >= old vocab size)
        sub_embs = []
        for sid in sub_ids:
            if sid < embed_weight.shape[0]:
                sub_embs.append(embed_weight[sid])
        
        if sub_embs:
            avg_emb = torch.stack(sub_embs).mean(dim=0)
            # Add small noise to break symmetry for syllables sharing sub-tokens
            avg_emb = avg_emb + torch.randn_like(avg_emb) * 0.01
            embed_weight[new_id] = avg_emb
            lm_head_weight[new_id] = avg_emb
            initialized += 1
    
    print(f"   🧠  Smart-init: {initialized}/{len(tokens_added)} syllable embeddings "
          f"from BPE sub-token averages")


# ═══════════════════════════════════════════════════════════════
#  DATA
# ═══════════════════════════════════════════════════════════════

class FlatTokenDataset(torch.utils.data.Dataset):
    def __init__(self, data, block_size):
        assert len(data) > block_size
        self.data = data
        self.block_size = block_size

    def __len__(self):
        return len(self.data) - self.block_size

    def __getitem__(self, idx):
        chunk = self.data[idx: idx + self.block_size + 1]
        return chunk[:self.block_size], chunk[1:]


def tokenize_with_qwen(lines, tokenizer):
    """Tokenize corpus lines into flat tensor of token IDs.
    
    v5 FIX: After adding syllable tokens, the tokenizer encodes each
    space-separated Vietnamese syllable as a SINGLE token, preventing
    BPE fragmentation.
    """
    ids = []
    for line in tqdm(lines, desc="Tokenizing"):
        if line.strip():
            ids.extend(tokenizer.encode(line, add_special_tokens=False))
    t = torch.tensor(ids, dtype=torch.long)
    print(f"  {len(lines):,} lines → {len(t):,} tokens")
    return t


def get_dataloaders(data, block_size, batch_size, num_workers=4, val_frac=0.10):
    # Shuffle before splitting to avoid bias (last poems may differ from rest)
    n = len(data)
    perm = torch.randperm(n)
    data = data[perm]
    split = int(n * val_frac)
    train_data, val_data = data[:-split], data[-split:]
    train_ds = FlatTokenDataset(train_data, block_size)
    val_ds = FlatTokenDataset(val_data, block_size)
    print(f"  Train: {len(train_ds):,} samples | Val: {len(val_ds):,} | Batch: {batch_size}")
    train_loader = torch.utils.data.DataLoader(
        train_ds, batch_size=batch_size, shuffle=True,
        pin_memory=True, num_workers=num_workers, drop_last=True)
    val_loader = torch.utils.data.DataLoader(
        val_ds, batch_size=batch_size, shuffle=False,
        pin_memory=True, num_workers=num_workers)
    return train_loader, val_loader


# ═══════════════════════════════════════════════════════════════
#  TRAINING UTILITIES
# ═══════════════════════════════════════════════════════════════

def get_lr(step, warmup, total, max_lr, min_lr):
    if step < warmup:
        return max_lr * (step + 1) / warmup
    if step >= total:
        return min_lr
    p = (step - warmup) / (total - warmup)
    return min_lr + 0.5 * (max_lr - min_lr) * (1 + math.cos(math.pi * p))


@torch.no_grad()
def evaluate(model, loader, device, n_batches=20):
    model.eval()
    loss, cnt = 0.0, 0
    for x, y in loader:
        if cnt >= n_batches: break
        x, y = x.to(device), y.to(device)
        with torch.autocast(device_type=device, dtype=torch.bfloat16):
            out = model(x, labels=y)
        loss += out.loss.item(); cnt += 1
    model.train()
    return loss / cnt


def save_checkpoint(model, tokenizer, optimizer, step, loss, stage, path):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    model.save_pretrained(path)
    tokenizer.save_pretrained(path)
    torch.save({
        "optimizer_state_dict": optimizer.state_dict(),
        "step": step,
        "loss": loss,
        "stage": stage,
    }, path / "training_state.pt")
    print(f"💾  Saved checkpoint to {path}")
    return path


# ═══════════════════════════════════════════════════════════════
#  CLOUD UPLOAD
# ═══════════════════════════════════════════════════════════════

def upload_checkpoints_gcs(local_dir, bucket_uri, stage):
    """Upload checkpoint directory to Google Cloud Storage."""
    from google.cloud import storage
    client = storage.Client()
    bucket_name = bucket_uri.replace("gs://", "").split("/")[0]
    prefix = "/".join(bucket_uri.replace("gs://", "").split("/")[1:])
    bucket = client.bucket(bucket_name)

    local_dir = Path(local_dir)
    for fpath in local_dir.rglob("*"):
        if fpath.is_file():
            blob_path = f"{prefix}/stage{stage}/{fpath.relative_to(local_dir)}"
            blob = bucket.blob(blob_path)
            blob.upload_from_filename(str(fpath))
            print(f"  ☁️  Uploaded: {blob_path}")

    print(f"✅  Stage {stage} uploaded to gs://{bucket_name}/{prefix}/")
    return f"gs://{bucket_name}/{prefix}/stage{stage}"


def upload_checkpoints_s3(local_dir, s3_uri, stage, endpoint_url=None):
    """Upload checkpoint directory to S3-compatible storage (AWS S3 or Cloudflare R2)."""
    import boto3
    kwargs = {}
    if endpoint_url:
        kwargs["endpoint_url"] = endpoint_url
        print(f"   Using endpoint: {endpoint_url}")
    elif os.environ.get("AWS_ENDPOINT_URL"):
        kwargs["endpoint_url"] = os.environ["AWS_ENDPOINT_URL"]

    s3 = boto3.client("s3", **kwargs)
    bucket_name = s3_uri.replace("s3://", "").split("/")[0]
    prefix = "/".join(s3_uri.replace("s3://", "").split("/")[1:])

    local_dir = Path(local_dir)
    for fpath in local_dir.rglob("*"):
        if fpath.is_file():
            key = f"{prefix}/stage{stage}/{fpath.relative_to(local_dir)}"
            s3.upload_file(str(fpath), bucket_name, key)
            print(f"  ☁️  Uploaded: s3://{bucket_name}/{key}")

    print(f"✅  Stage {stage} uploaded to s3://{bucket_name}/{prefix}/")
    return f"s3://{bucket_name}/{prefix}/stage{stage}"


def upload_checkpoints(local_dir, stage):
    """Upload to cloud storage — supports GCS, AWS S3, and Cloudflare R2."""
    gcs_bucket = os.environ.get("GCS_BUCKET")
    s3_bucket = os.environ.get("S3_BUCKET")
    s3_endpoint = os.environ.get("S3_ENDPOINT")

    if gcs_bucket:
        return upload_checkpoints_gcs(local_dir, gcs_bucket, stage)
    elif s3_bucket:
        return upload_checkpoints_s3(local_dir, s3_bucket, stage, endpoint_url=s3_endpoint)
    else:
        print("⚠️  No GCS_BUCKET or S3_BUCKET set — checkpoint saved locally only")
        print("   Set one of: GCS_BUCKET=gs://...  or  S3_BUCKET=s3://... + S3_ENDPOINT=https://...")
        return str(local_dir)


# ═══════════════════════════════════════════════════════════════
#  v4.2.3 TRAINING IMPROVEMENTS (P6, P7, P8)
# ═══════════════════════════════════════════════════════════════

def build_token_weight_tensor(vocab_size, device, 
                               generated_ids: set, control_ids: set,
                               tag_weight: float, lb_bonus: float):
    """
    P6 + P8: Build per-class loss weight tensor.
    
    Control tokens (prompt-only tags like [RHYME:X], [TONE:...], <|reply|>)
    get reduced weight because the model never generates them at inference.
    <|end|> and <|linebreak|> ARE generated → full weight.
    <|linebreak|> gets extra bonus (P8).
    All content tokens (Qwen native vocab + syllable tokens) → 1.0×.
    
    Returns: tensor of shape (vocab_size,) for F.cross_entropy(weight=...)
    """
    token_weight = torch.ones(vocab_size, device=device)
    for cid in control_ids:
        if cid < vocab_size and cid not in generated_ids:
            token_weight[cid] = tag_weight
    # P8: linebreak bonus (applied even if in generated_ids)
    for lb_id in generated_ids:
        if lb_id < vocab_size:
            token_weight[lb_id] = 1.0 + lb_bonus
    return token_weight


def compute_diversity_loss(logits, input_ids, device, 
                            window, n_samples, control_ids: set):
    """
    P7: Penalize high logits on content tokens that appeared recently.
    
    Uses raw logit mean (no softmax) for memory efficiency.
    Samples random (batch, position) pairs to keep overhead ~5%.
    Excludes control tokens (prompt-only tags) and pad from diversity penalty.
    """
    B, T = input_ids.shape
    b_idx = torch.randint(0, B, (n_samples,), device=device)
    t_idx = torch.randint(1, T, (n_samples,), device=device)
    div_sum = torch.tensor(0.0, device=device)
    div_n = 0
    
    for i in range(n_samples):
        bi, ti = b_idx[i].item(), t_idx[i].item()
        start_t = max(0, ti - window)
        recent = input_ids[bi, start_t:ti]
        # Exclude control tokens from diversity tracking
        content_mask = torch.ones(len(recent), dtype=torch.bool, device=device)
        for cid in control_ids:
            content_mask = content_mask & (recent != cid)
        content_mask = content_mask & (recent != 0)  # exclude pad
        if not content_mask.any():
            continue
        unique_ids = recent[content_mask].unique()
        div_sum = div_sum + logits[bi, ti, unique_ids].mean()
        div_n += 1
    
    if div_n > 0:
        return div_sum / div_n
    return torch.tensor(0.0, device=device)


# ═══════════════════════════════════════════════════════════════
#  TRAINING LOOP
# ═══════════════════════════════════════════════════════════════

def train(stage=1, resume_from=None, max_steps_override=None):
    from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

    SC = STAGE_CONFIGS[stage]
    TC = TRAIN_CONFIG
    dev = TC["device"]

    max_steps = max_steps_override if max_steps_override else SC["max_steps"]
    batch_size = TC["batch_size"]
    grad_accum = TC["gradient_accumulation_steps"]
    corpus_path = STAGE_CORPUS[stage]

    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)

    if not corpus_path.exists():
        raise FileNotFoundError(f"Corpus not found: {corpus_path}. "
                                f"Did you COPY it into the Docker image?")

    print(f"\n{'='*60}\n🚀  Qwen2.5-1.5B QLoRA v5 FIXED — Stage {stage}\n{'='*60}")
    print(f"   Steps: {max_steps:,} | Batch: {batch_size}×{grad_accum}={batch_size*grad_accum} | "
          f"Block: {TC['block_size']} | LR: {SC['lr']}")
    print(f"   Corpus: {corpus_path.name} (LB-only)")
    print(f"   GPU: {torch.cuda.get_device_name(0) if dev == 'cuda' else 'CPU'}")
    if dev == 'cuda':
        print(f"   VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

    # ── Load model + tokenizer ──
    print(f"\n📦  Loading {MODEL_ID}...")
    hf_token = os.environ.get("HF_TOKEN")
    if not hf_token:
        raise RuntimeError("HF_TOKEN environment variable not set! Set it to your HuggingFace token.")
    cache_dir = os.environ.get("HF_HOME", os.path.expanduser("~/.cache/huggingface"))
    print(f"   Cache: {cache_dir}")
    bnb_config = BitsAndBytesConfig(**QLORA_CONFIG)
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
        dtype=torch.bfloat16,
        token=hf_token,
        cache_dir=cache_dir,
    )

    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True, 
                                               token=hf_token, cache_dir=cache_dir)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # ── Add 335 special tokens ──
    print(f"\n🔤  Adding special tokens...")
    special_tokens = build_special_tokens(str(corpus_path))
    num_added = tokenizer.add_tokens(special_tokens, special_tokens=True)
    print(f"   Added {num_added} control tokens | Vocab: {len(tokenizer):,}")

    # ── Resize model for added control tokens (no syllable tokens) ──
    # Control tokens (214) still need embedding slots. Syllable tokens are NOT
    # added — Qwen's native tokenizer handles Vietnamese, BPE fragments are
    # fixed at inference via join_bpe_fragments() in eval_qwen.py.
    model.resize_token_embeddings(len(tokenizer))
    vocab_size = len(tokenizer)
    print(f"   Vocab: {vocab_size:,} (Qwen native + {num_added} control tokens)")
    
    # ── Map key token IDs in new vocab ──
    # These IDs may change after adding tokens; look them up by string
    pad_id = tokenizer.pad_token_id
    reply_id = tokenizer.encode("<|reply|>", add_special_tokens=False)[0] if "<|reply|>" in tokenizer.get_vocab() else 2
    end_id = tokenizer.encode("<|end|>", add_special_tokens=False)[0] if "<|end|>" in tokenizer.get_vocab() else 3
    lb_id = tokenizer.encode("<|linebreak|>", add_special_tokens=False)[0] if "<|linebreak|>" in tokenizer.get_vocab() else 9
    start_id = tokenizer.encode("<|start|>", add_special_tokens=False)[0] if "<|start|>" in tokenizer.get_vocab() else 1
    
    # ── Identify control token IDs (prompt-only tags → reduced loss weight) ──
    # Qwen base vocab (0 to original_vocab_size-1) = content → 1.0×
    # Our added special tokens = control → 0.3× (except <|end|> and <|lb|>)
    # Syllable tokens = content → 1.0×
    original_vocab_size = model.config.vocab_size if hasattr(model.config, 'vocab_size') else 151936
    
    # Collect all control token IDs (our added special tokens, not syllables)
    control_ids = set()
    for token_str in special_tokens:
        tid = tokenizer.encode(token_str, add_special_tokens=False)
        if tid:
            control_ids.add(tid[0])
    
    generated_ids = {end_id, lb_id}  # only <|end|> and <|linebreak|> are generated at inference
    
    # Syllable tokens start after control tokens — they're content
    # Any ID >= original_vocab_size that's NOT in control_ids is a syllable token
    content_start = original_vocab_size  # for diversity loss filtering
    
    print(f"   Token IDs: pad={pad_id} reply={reply_id} end={end_id} lb={lb_id} start={start_id}")
    print(f"   Original Qwen vocab: {original_vocab_size:,} | Control tokens: {len(control_ids)} | Generated: {generated_ids}")
    print(f"   Content start ID: {content_start}")

    # ── Build P6+P8 loss weight tensor ──
    token_weight = build_token_weight_tensor(
        vocab_size, dev, generated_ids, control_ids, TAG_LOSS_WEIGHT, LINEBREAK_BONUS
    )
    print(f"   P6+P8: Content-weighted loss (tags ×{TAG_LOSS_WEIGHT}, <|end|> ×1.0, "
          f"<|lb|> ×{1.0+LINEBREAK_BONUS})")
    print(f"   P7: Diversity loss (weight={DIVERSITY_LOSS_WEIGHT}, "
          f"samples={DIVERSITY_SAMPLES}/step, warmup={DIVERSITY_WARMUP})")

    # ── Apply LoRA ──
    print(f"\n🎯  Applying LoRA (r={LORA_CONFIG['r']}, alpha={LORA_CONFIG['lora_alpha']})...")
    model = prepare_model_for_kbit_training(model)
    model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={"use_reentrant": False})
    lora_config = LoraConfig(**LORA_CONFIG)
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    # ── Load data ──
    print(f"\n📖  Corpus: {corpus_path}")
    with open(corpus_path, encoding="utf-8") as f:
        lines = [l.strip() for l in f if l.strip()]

    data = tokenize_with_qwen(lines, tokenizer)
    train_loader, val_loader = get_dataloaders(data, TC["block_size"], batch_size, 
                                                  num_workers=TC["num_workers"], val_frac=0.10)

    # ── Optimizer ──
    opt = torch.optim.AdamW(model.parameters(), lr=SC["lr"], betas=(0.9, 0.95),
                             weight_decay=0.01)

    # ── Resume ──
    start_step = 0
    if resume_from:
        from peft import PeftModel
        resume_path = Path(resume_from)
        if not resume_path.exists():
            resume_path = CHECKPOINT_DIR / resume_from
        print(f"\n📂  Resuming from: {resume_path}")
        model = PeftModel.from_pretrained(model, resume_path)
        ckpt = torch.load(str(resume_path / "training_state.pt"), map_location=dev, weights_only=False)
        opt.load_state_dict(ckpt["optimizer_state_dict"])
        start_step = ckpt.get("step", 0)
        SC["max_steps"] = max(max_steps, start_step + 1000)
        max_steps = SC["max_steps"]
        print(f"   Step: {start_step} | Adjusted max_steps: {max_steps}")

    # ── Training ──
    print(f"\n{'='*60}\n🔥  TRAINING (v5 FIXED with v4.2.3 improvements)\n{'='*60}\n")
    model.train()
    step, best_val, plateau_count = start_step, float("inf"), 0
    loss_sum, loss_cnt = 0.0, 0
    t0 = time.time()
    it = iter(train_loader)
    pbar = tqdm(total=TC["eval_interval"], desc=f"  Steps 0-{TC['eval_interval']}", unit="s", leave=False)
    micro_step = 0

    while step < max_steps:
        try:
            x, y = next(it)
        except StopIteration:
            it = iter(train_loader); x, y = next(it)
        x, y = x.to(dev), y.to(dev)

        lr = get_lr(step, TC["warmup_steps"], max_steps, SC["lr"], TC["min_lr"])
        for pg in opt.param_groups: pg["lr"] = lr

        # ── v4.2.3: Scheduled Sampling with control token protection ──
        use_teacher_prob = max(0.5, 1.0 - step / max_steps * 0.5)
        if use_teacher_prob < 1.0:
            with torch.no_grad():
                with torch.autocast(device_type=dev, dtype=torch.bfloat16):
                    out_sample = model(x)
                # out_sample.logits shape: (B, T, V)
                model_tokens = out_sample.logits.argmax(dim=-1)
            x_model = torch.cat([x[:, :1], model_tokens[:, :-1]], dim=1)
            mask = torch.rand(x.shape, device=dev) < use_teacher_prob
            # PROTECT control tokens: never replace them during scheduled sampling
            is_control = torch.zeros_like(x, dtype=torch.bool)
            for cid in control_ids:
                is_control = is_control | (x == cid)
            mask = mask | is_control
            x_input = torch.where(mask, x, x_model)
        else:
            x_input = x

        # ── Forward ──
        with torch.autocast(device_type=dev, dtype=torch.bfloat16):
            out = model(x_input)
            logits = out.logits  # (B, T, V)

            # ── P6+P8: Content-weighted cross-entropy loss ──
            loss = F.cross_entropy(
                logits.view(-1, vocab_size), y.view(-1),
                ignore_index=pad_id, weight=token_weight
            )

            # ── P7: N-gram diversity loss ──
            if step >= DIVERSITY_WARMUP:
                div_loss = compute_diversity_loss(
                    logits, x_input, dev,
                    DIVERSITY_WINDOW, DIVERSITY_SAMPLES, control_ids
                )
                loss = loss + DIVERSITY_LOSS_WEIGHT * div_loss
        
        loss = loss / grad_accum
        loss.backward()
        micro_step += 1

        if micro_step % grad_accum == 0:
            torch.nn.utils.clip_grad_norm_(model.parameters(), TC["grad_clip"])
            opt.step()
            opt.zero_grad()
            step += 1
            loss_sum += loss.item() * grad_accum
            loss_cnt += 1
            pbar.update(1)
            pbar.set_postfix({"loss": f"{loss.item()*grad_accum:.4f}"})

        if step > 0 and step % TC["eval_interval"] == 0 and micro_step % grad_accum == 0:
            train_loss = loss_sum / loss_cnt
            val_loss = evaluate(model, val_loader, dev)
            is_best = val_loss < best_val
            trend = "📉" if is_best else "➡️"
            best_val = min(best_val, val_loss)
            plateau_count = 0 if is_best else plateau_count + 1

            pbar.close()
            status = f"loss={train_loss:.4f} val={val_loss:.4f} {trend} lr={lr:.2e}"
            patience = SC.get("patience", 0)
            if patience > 0:
                status += f"  [{plateau_count}/{patience}]"
            elapsed = time.time() - t0
            eta = (elapsed / max(1, step)) * (max_steps - step)
            print(f"── Step {step:5d}/{max_steps} ({elapsed:.0f}s, ETA: {eta:.0f}s) ── {status}")
            loss_sum = 0.0; loss_cnt = 0

            if is_best:
                p = save_checkpoint(model, tokenizer, opt, step, val_loss, stage,
                                    CHECKPOINT_DIR / f"qwen_stage{stage}_best")
                print(f"   🏆  Best! val={val_loss:.4f} → {p}")

            if patience > 0 and plateau_count >= patience:
                print(f"   ⏹️  Plateau ({patience} evals) — stopping")
                break

            if step < max_steps:
                nxt = min(step + TC["eval_interval"], max_steps)
                pbar = tqdm(total=TC["eval_interval"], desc=f"  Steps {step}-{nxt}", unit="s", leave=False)

        if step > 0 and step % 2000 == 0:
            save_checkpoint(model, tokenizer, opt, step, float(loss.item()) * grad_accum, stage,
                            CHECKPOINT_DIR / f"qwen_stage{stage}_step{step}")

    pbar.close()

    # ── Final save + cloud upload ──
    final_path = save_checkpoint(model, tokenizer, opt, step, best_val, stage,
                                  CHECKPOINT_DIR / f"qwen_stage{stage}_final")

    elapsed = time.time() - t0
    print(f"\n{'='*60}")
    print(f"✅  Stage {stage} complete! {elapsed:.0f}s | Best val: {best_val:.4f}")
    print(f"{'='*60}\n")

    # ── Upload checkpoints to cloud storage ──
    print("☁️  Uploading checkpoints...")
    cloud_path = upload_checkpoints(CHECKPOINT_DIR, stage)
    print(f"📍  Cloud path: {cloud_path}")

    return str(final_path)


# ═══════════════════════════════════════════════════════════════
#  MAIN
# ═══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Qwen2.5 QLoRA v5 FIXED — containerized for Salad")
    parser.add_argument("--stage", type=int, choices=[1, 2], default=1)
    parser.add_argument("--resume", type=str, default=None, help="Resume from checkpoint dir")
    parser.add_argument("--device", type=str, default="cuda")
    parser.add_argument("--max-steps", type=int, default=None, help="Override max steps (for smoke testing)")
    args = parser.parse_args()

    TRAIN_CONFIG["device"] = args.device if torch.cuda.is_available() else "cpu"

    # Env var override for max steps (works well with Docker -e flag)
    max_steps = args.max_steps or int(os.environ.get("TRAIN_MAX_STEPS", "0")) or None

    # Stage 1
    result = train(stage=args.stage, resume_from=args.resume, max_steps_override=max_steps)

    # Auto-chain: if stage 1 completed successfully and no explicit resume,
    # run stage 2 automatically (saves starting a second container)
    if args.stage == 1 and not args.resume:
        auto_chain = os.environ.get("AUTO_CHAIN_STAGES", "0")
        if auto_chain == "1":
            stage1_best = CHECKPOINT_DIR / "qwen_stage1_best"
            if stage1_best.exists():
                print("\n" + "="*60)
                print("🔗  AUTO-CHAIN: Stage 1 → Stage 2")
                print("="*60 + "\n")
                train(stage=2, resume_from=str(stage1_best), max_steps_override=max_steps)
